project/searchStackOverFlow/searchQuestions/urls.py
from django.urls import path,include
from . import views

app_name    = 'searchQuestions'
urlpatterns = [
    path('',views.home, name = 'home'),
    path('queryForm/',views.handleQueryForm,name="index"),
    path('results/',views.paginateResults,name="results"),
]

project/searchStackOverFlow/searchStackOverFlow/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('searchQuestions.urls')),
]

project/searchStackOverFlow/searchQuestions/models.py
from django.db import models

# Create your models here.
class Question(models.Model):

    QUESTIONS_BY_FIELDS = [
        ('NO_ANS','no-answers'),  #questions with no answers
        ('UN_ANS','un_answered'), #questions that site considers unanswered 
        ('DEFAULT','default'),    #questions without any fields 
        ('FEATURED','featured'),  #questions that are featured in site
        ('RELATED','related'),    #questions that are related to set of ids
        ('LINKED','linked'),      #question that are linked to set of ids
    ]
    question = models.CharField(max_length=50,choices=QUESTIONS_BY_FIELDS,default='DEFAULT')
    ids      = models.CharField(max_length=50,blank=True) #to specify set of ids for questions

    def __str__(self):
        return self.id

project/searchStackOverFlow/searchQuestions/forms.py
from django.forms import ModelForm
from .models import Question

class QuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = '__all__'
        

project/searchStackOverFlow/searchQuestions/views.py
from django.shortcuts import render
from .forms import QuestionForm
from django.core.paginator import Paginator
# my_helper functions for views
from .helperFunctions import  handleQuesTypes, checkAvailability


#created at global scope, so that can access this variable
questionsList = []

"""Create your views here."""

# provides home page
def home(request):
    return render(request, 'searchQuestions/home.html')


# handles query form 
def handleQueryForm(request):
    #if query form is submitted
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            # retrieve fields from request
            question_type = request.POST.get('question')
            ids = request.POST.get('ids')
            form.save(commit=True)
            # list of objects
            global questionsList
            # returns list/None after handling a requested query
            questionsList = handleQuesTypes(question_type, ids)
            # returns True/False for data availability
            print(checkAvailability(questionsList))
            # if data is available
            if(checkAvailability(questionsList)):
                context = {"msg": "Query is Saved successfully"}
            #if there is no data
            else:
                context = {'msg2':"Query cannot be processed cause, there is no such content available"}
            return render(request, 'searchQuestions/success.html', context)
    else:
        # if query form is requested
        form = QuestionForm()
        context = {'form': form, 'default':"'default' means simply Get all questions on the site."}
        return render(request, 'searchQuestions/index.html', context)



# handles the pagination of results
def paginateResults(request):
    if request.method == "GET":
        paginator = Paginator(questionsList, 25)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context = {'page_obj': page_obj}
        return render(request, 'searchQuestions/searchResults.html', context)

project/searchStackOverFlow/searchQuestions/templates/searchQuestions/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
      crossorigin="anonymous"
    />
    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
      crossorigin="anonymous"
    ></script>
  </head>
  <body  class="container" style="padding-top: 70px;">
    <nav class="navbar navbar-dark bg-dark fixed-top">
      <!-- Navbar content -->
      <a class="navbar-brand" href="#">Search StackOverflow</a>
      <div>
      <a href="{% url 'searchQuestions:home' %}"  class="btn btn-outline-dark text-white border-light" role="button" aria-pressed="true">Home</a>
      <a href="{% url 'searchQuestions:index' %}" class="btn btn-outline-dark text-white border-light" role="button" aria-pressed="true">Back to Query</a></div>
    </nav>
    {% block body %}

     {% endblock body %}
  </body>
</html>

project/searchStackOverFlow/searchQuestions/templates/searchQuestions/home.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Home</title>
  </head>
  <body class="container">
    <div class="jumbotron">
        <h1 class="display-4">Search Stack Overflow</h1>
        <h4>This is a small web app were users can search questions and on stack overflow.</h4>
        <hr class="my-4">
        <h5>Get the details of questions like, title, question ID, answered or not, answers count if it's answered etc.</h5>
        <p class="lead">
          <a class="btn btn-dark btn-lg" href="{% url 'searchQuestions:index' %}" role="button">Go to app</a>
        </p>
    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

project/searchStackOverFlow/searchQuestions/templates/searchQuestions/index.html
{% extends 'searchQuestions/base.html' %}

{% load crispy_forms_tags %}

{% block body %}

    <form action="{% url 'searchQuestions:index' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.question.errors }}
        <!-- question_type dropdown -->
        <h2>Select Question type: </h2>{{ form.question|as_crispy_field }}
        <div class="alert alert-warning" role="alert">
            Note: For "Linked" and "Related" type you need to specify
            ids cause, such type of questions can only be identified
            by a set of ids.
          </div>
        <div>
        <div class="alert alert-success" role="alert">{{ default }}</div>
        <div>
        {{ form.ids.errors }}
        <!-- ids field to search questions of specific ids -->
        <h2>Enter the ids if you want to search specific ids of questions:</h2>
        {{ form.ids|as_crispy_field  }}
        <p>NOTE:-If you want to search specific ids of questions,
        enter them with " " separated</p>
        <!-- search button for questons -->
        <input class="btn-secondary btn-lg" type="submit" value="Search">
    </form>
{% endblock body %}

project/searchStackOverFlow/searchQuestions/templates/searchQuestions/searchResults.html
{% extends 'searchQuestions/base.html' %} 


{% block body %}

<!-- Question cards here -->
{% for item in page_obj  %}
    {% for keys,value in item.items %}
        {% ifequal keys 'title' %}
        
        <div class="card border border-dark bg-dark text-white text-white">
            <h5 class="card-header " style="color: rgb(216, 216, 216);">Question title: {{ value }}</h5>{% endifequal %}
        {% ifequal keys 'question_id'%}
            <div class="card-body py-0">
            <h5 class="card-title mt-2"><p class="text-right">Question ID: {{ value }}</p></h5>{% endifequal %}
        {% ifequal keys 'is_answered'%}
            <h5 class="card-text">Is Answered: {{ value }}</h5>{% endifequal %}
        {% ifequal keys 'answer_count'%}
            <h5 class="card-text">Answer's Count: {{ value }}</h5>{% endifequal %}
        {% ifequal keys 'link'%}
            <a href={{ value }} class="btn  btn-success text-white mb-3">Go to stackoverflow</a>{% endifequal %}
            </div>
        </div>
    
    {% endfor %}
    
{% endfor %}



<!-- pagination part here -->
<div>
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li><a class="page-link  border border-primary rounded" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
        {% endif %}
        <li class="page-item active ">
        <span class="page-link">{{page_obj.number}}</span>
        </li>
        {% if page_obj.has_next %}
        <li><a class="page-link border border-primary rounded" href="?page={{ page_obj.next_page_number }}">Next</a></li>
        {% endif %}
    </ul>
</div>

{% endblock body %}

project/searchStackOverFlow/searchQuestions/templates/searchQuestions/success.html
{% extends 'searchQuestions/base.html' %} 

{% block body %}
{% if msg %}
<h1 style =  "align-content: center;">{{ msg }}</h1>
<form action="{% url 'searchQuestions:results' %}" method="GET" enctype="multipart/form-data">
    <input type="submit" class="btn  btn-success text-white" value="Get The Results">
</form>
{% elif msg2 %}
<h1 style =  "align-content: center;">{{ msg2 }}</h1>
<form action="{% url 'searchQuestions:index' %}" method="GET" enctype="multipart/form-data">
    <input type="submit" class="btn  btn-success text-white" value="Back to Query Again">
</form>
{% endif %}
{% endblock body %}